export const elements = [
  { id: 1, group:'Humanitarian', label: 'A', description: 'Tecnologias adequadas ao mundo em desenvolvimento', video:"https://www.youtube.com/embed/FP8iXAjaYJ8" },
  { id: 3, group:'Humanitarian', label: 'Cw', description: 'Química para o bem-estar', video: "https://www.youtube.com/embed/link" },
  { id: 11, group:'Humanitarian', label: 'Sw', description: 'Acesso à água segura e confiável', video: "https://www.youtube.com/embed/link" },
  { id: 19, group:'Humanitarian', label: 'Bf', description: 'Química para a produção de alimentos benignos e nutritivos', video: "https://www.youtube.com/embed/link" },
  { id: 37, group:'Humanitarian', label: 'J', description: 'Garantir justiça ambiental, segurança e oportunidades equitativas', video: "https://www.youtube.com/embed/link" },
  { id: 55, group:'Humanitarian', label: 'Pc', description: 'Química para preservar o carbono natural e outros ciclos biogeoquímicos', video: "https://www.youtube.com/embed/link" },
  { id: 73, group:'Humanitarian', label: 'Wo', description: 'Sem produtos químicos em prol de guerra ou opressão', video: "https://www.youtube.com/embed/link" },
  { id: 4, group:'Humanitarian', label: 'Dd', description: 'Design para evitar dependência', video: "https://www.youtube.com/embed/link" },
  { id: 12, group:'Humanitarian', label: 'Fg', description: 'Garantir o acesso a recursos materiais para as gerações futuras', video: "https://www.youtube.com/embed/link" },
  { id: 20, group:'Humanitarian', label: 'Tc', description: 'Transparência na comunicação química', video: "https://www.youtube.com/embed/link" },
  { id: 38, group:'Humanitarian', label: 'Cs', description: 'Química para edifícios e edificações sustentáveis', video: "https://www.youtube.com/embed/link" },
  { id: 56, group:'Humanitarian', label: 'Ic', description: 'O código molecular de um indivíduo pertence a esse indivíduo', video: "https://www.youtube.com/embed/link" },
  { id: 74, group:'Humanitarian', label: 'Nc', description: 'Códigos moleculares da natureza pertencem ao mundo', video: "https://www.youtube.com/embed/link" },
  { id: 21, group:'PreventWaste', label: 'Wu', description: 'Aproveitamento e valorização de resíduos', video: "https://www.youtube.com/embed/link" },
  { id: 39, group:'PreventWaste', label: 'Op', description: 'Sínteses “one-pot” ou sínteses em um único vaso reacional', video: "https://www.youtube.com/embed/link" },
  { id: 57, group:'PreventWaste', label: 'Pi', description: 'Intensificação de processo', video: "https://www.youtube.com/embed/link" },
  { id: 75, group:'PreventWaste', label: 'Ss', description: 'Autosseparação', video: "https://www.youtube.com/embed/link" },
  { id: 22, group:'AtomEconomy', label: 'Sa', description: 'Automontagem molecular', video: "https://www.youtube.com/embed/link" },
  { id: 40, group:'AtomEconomy', label: 'Ip', description: 'Processos integrados', video: "https://www.youtube.com/embed/link" },
  { id: 58, group:'AtomEconomy', label: 'As', description: 'Síntese aditiva', video: "https://www.youtube.com/embed/link" },
  { id: 76, group:'AtomEconomy', label: 'W', description: 'Derivados não-covalentes / transformação de forças fracas', video: "https://www.youtube.com/embed/link" },
  { id: 23, group:'LessHazardous', label: 'Ru', description: 'Reduzir o uso de materiais nocivos', video: "https://www.youtube.com/embed/link" },
  { id: 41, group:'LessHazardous', label: 'Gc', description: 'Geração e consumo in situ de materiais nocivos', video: "https://www.youtube.com/embed/link" },
  { id: 59, group:'LessHazardous', label: 'Ch', description: 'Funcionalização da ligação C-H', video: "https://www.youtube.com/embed/link" },
  { id: 77, group:'LessHazardous', label: 'Is', description: 'Segurança e proteção inerentes', video: "https://www.youtube.com/embed/link" },
  { id: 24, group:'MolecularDesign', label: 'Dg', description: 'Diretrizes de design', video: "https://www.youtube.com/embed/link" },
  { id: 42, group:'MolecularDesign', label: 'Cm', description: 'Modelos computacionais', video: "https://www.youtube.com/embed/link" },
  { id: 60, group:'MolecularDesign', label: 'Ba', description: 'Biodisponibilidade / ADME (absorção, distribuição, metabolismo, excreção)', video: "https://www.youtube.com/embed/link" },
  { id: 78, group:'MolecularDesign', label: 'Ts', description: 'Triagem de alto rendimento (empírico/in vivo/in vitro)', video: "https://www.youtube.com/embed/link" },
  { id: 25, group:'Solvents', label: 'Aq', description: 'Solventes aquosos e de base biológica', video: "https://www.youtube.com/embed/link" },
  { id: 43, group:'Solvents', label: 'Ii', description: 'Líquidos iônicos/solventes não voláteis', video: "https://www.youtube.com/embed/link" },
  { id: 61, group:'Solvents', label: 'Sc', description: 'Fluidos sub e supercríticos', video: "https://www.youtube.com/embed/link" },
  { id: 79, group:'Solvents', label: 'S', description: 'Solventes “inteligentes” (obedientes/ajustáveis)', video: "https://www.youtube.com/embed/link" },
  { id: 26, group: 'Energy', label: 'Ee', description: 'Síntese e processamento eficientes de energia e material', video: "https://www.youtube.com/embed/link" },
  { id: 44, group: 'Energy', label: 'R', description: 'Entradas de energia renovável / sem carbono', video: "https://www.youtube.com/embed/link" },
  { id: 62, group: 'Energy', label: 'Es', description: 'Materiais de armazenamento e transmissão de energia', video: "https://www.youtube.com/embed/link" },
  { id: 80, group: 'Energy', label: 'V', description: 'Aproveitamento e valorização de energia residual', video: "https://www.youtube.com/embed/link" },
  { id: 27, group: 'Renewable', label: 'Ib', description: 'Biorrefinaria integrada', video: "https://www.youtube.com/embed/link" },
  { id: 45, group: 'Renewable', label:'C', description: 'Dióxido de carbono e outras matérias-primas C1', video: "https://www.youtube.com/embed/link" },
  { id: 63, group: 'Renewable', label: 'Sb', description: 'Biologia sintética', video: "https://www.youtube.com/embed/link" },
  { id: 81, group: 'Renewable', label: 'Bt', description: 'Transformação habilitada biologicamente', video: "https://www.youtube.com/embed/link" },
  { id: 28, group: 'Catalysis', label: 'E', description: 'Enzimas', video: "https://www.youtube.com/embed/link" },
  { id: 46, group: 'Catalysis', label: 'Ac', description: 'Catálise baseada em metais abundantes na terra', video: "https://www.youtube.com/embed/link" },
  { id: 64, group: 'Catalysis', label: 'Ht', description: 'Catálise heterogênea', video: "https://www.youtube.com/embed/link" },
  { id: 82, group: 'Catalysis', label: 'Hm', description: 'Catálise homogênea', video: "https://www.youtube.com/embed/link" },
  { id: 29, group: 'Degradation', label: 'Bm', description: 'Metabólitos benignos', video: "https://www.youtube.com/embed/link" },
  { id: 47, group: 'Degradation', label: 'Md', description: 'Estímulos de degradação molecular', video: "https://www.youtube.com/embed/link" },
  { id: 65, group: 'Degradation', label: 'Dp', description: 'Polímeros degradáveis e outros materiais', video: "https://www.youtube.com/embed/link" },
  { id: 83, group: 'Degradation', label: 'Pd', description: 'Ferramentas de previsão e design', video: "https://www.youtube.com/embed/link" },
  { id: 30, group: 'Measurement', label: 'Sn', description: 'Sensores', video: "https://www.youtube.com/embed/link" },
  { id: 48, group: 'Measurement', label: 'Co', description: 'Controle e otimização em processo', video: "https://www.youtube.com/embed/link" },
  { id: 66, group: 'Measurement', label: 'Ex', description: 'Expossoma', video: "https://www.youtube.com/embed/link" },
  { id: 84, group: 'Measurement', label: 'Ga', description: 'Química analítica verde', video: "https://www.youtube.com/embed/link" },
  { id: 5, group: 'Frameworks', label: 'B', description: 'Biomimética', video: "https://www.youtube.com/embed/link" },
  { id: 13, group: 'Frameworks', label: 'Ce', description: 'Economia circular', video: "https://www.youtube.com/embed/link" },
  { id: 31, group: 'Frameworks', label: 'Bd', description: 'Benigno por design', video: "https://www.youtube.com/embed/link" },
  { id: 49, group: 'Frameworks', label: 'Ie', description: 'Ecologia industrial', video: "https://www.youtube.com/embed/link" },
  { id: 67, group: 'Frameworks', label: 'Tg', description: 'Design transgeracional', video: "https://www.youtube.com/embed/link" },
  { id: 85, group: 'Frameworks', label: 'Be', description: 'Economia de base biológica sustentável', video: "https://www.youtube.com/embed/link" },
  { id: 6, group: 'Market', label: 'Cb', description: 'Análise de custo-benefício do ciclo de vida', video: "https://www.youtube.com/embed/link" },
  { id: 14, group: 'Market', label: 'Fc', description: 'Contabilização integral de custos', video: "https://www.youtube.com/embed/link" },
  { id: 32, group: 'Market', label: 'Hc', description: 'Taxa de danos / imposto sobre carbono', video: "https://www.youtube.com/embed/link" },
  { id: 50, group: 'Market', label: 'Dc', description: 'Carga de esgotamento', video: "https://www.youtube.com/embed/link" },
  { id: 68, group: 'Market', label: 'Rf', description: 'Financiamento de pesquisa sustentada', video: "https://www.youtube.com/embed/link" },
  { id: 86, group: 'Market', label: 'Ci', description: 'Investimento financeiro', video: "https://www.youtube.com/embed/link" },
  { id: 7, group: 'Metrics', label: 'Ae', description: 'Economia de átomos', video: "https://www.youtube.com/embed/link" },
  { id: 15, group: 'Metrics', label: 'Ef', description: 'Fator E ou fator ambiental', video: "https://www.youtube.com/embed/link" },
  { id: 33, group: 'Metrics', label: 'Ff', description: 'Fator F ou fator função/performance', video: "https://www.youtube.com/embed/link" },
  { id: 51, group: 'Metrics', label: 'Ql', description: 'Métricas qualitativas', video: "https://www.youtube.com/embed/link" },
  { id: 69, group: 'Metrics', label: 'Qn', description: 'Métricas quantitativas', video: "https://www.youtube.com/embed/link" },
  { id: 87, group: 'Metrics', label: 'Bb', description: 'Carga química corporal', video: "https://www.youtube.com/embed/link" },
  { id: 8, group: 'Policie', label: 'Pr', description: 'Responsabilidade estendida do produtor', video: "https://www.youtube.com/embed/link" },
  { id: 16, group: 'Policie', label: 'Pb', description: 'Regulamentação baseada em propriedade', video: "https://www.youtube.com/embed/link" },
  { id: 34, group: 'Policie', label: 'Ct', description: 'Transparência química', video: "https://www.youtube.com/embed/link" },
  { id: 52, group: 'Policie', label: 'Cl', description: 'Gestão sustentável de produtos químicos / Leasing químico', video: "https://www.youtube.com/embed/link" },
  { id: 70, group: 'Policie', label: 'Se', description: 'Regulamentos autoaplicáveis', video: "https://www.youtube.com/embed/link" },
  { id: 88, group: 'Policie', label: 'I', description: 'Ecossistema de inovação - tradução do laboratório para o comércio', video: "https://www.youtube.com/embed/link" },
  { id: 9, group: 'Tools', label: 'Ea', description: 'Análise epidemiológica e saúde do ecossistema', video: "https://www.youtube.com/embed/link" },
  { id: 17, group: 'Tools', label: 'Aa', description: 'Avaliação de alternativas', video: "https://www.youtube.com/embed/link" },
  { id: 35, group: 'Tools', label: 'Lc', description: 'Seleção de solvente', video: "https://www.youtube.com/embed/link" },
  { id: 53, group: 'Tools', label: 'So', description: 'Pegada química', video: "https://www.youtube.com/embed/link" },
  { id: 71, group: 'Tools', label: 'Cf', description: 'Regulamentos autoaplicáveis', video: "https://www.youtube.com/embed/link" },
  { id: 89, group: 'Tools', label: 'Et', description: 'Educação em toxicologia e pensamento sistêmico', video: "https://www.youtube.com/embed/link" },
  { id: 2, group: 'Noble', label: 'Ho', description: 'Juramento hipocrático para química', video: "https://www.youtube.com/embed/link" },
  { id: 10, group: 'Noble', label: 'P', description: 'Design para o futuro', video: "https://www.youtube.com/embed/link" },
  { id: 18, group: 'Noble', label: 'Lp', description: 'Produtos e processos compatíveis com a vida', video: "https://www.youtube.com/embed/link" },
  { id: 36, group: 'Noble', label: 'Z', description: 'Desperdício zero', video: "https://www.youtube.com/embed/link" },
  { id: 54, group: 'Noble', label: 'Fi', description: 'Química é equitativa e totalmente inclusiva', video: "https://www.youtube.com/embed/link" },
  { id: 72, group: 'Noble', label: 'De', description: 'Benefícios distribuídos equitativamente', video: "https://www.youtube.com/embed/link" },
  { id: 90, group: 'Noble', label: 'K', description: 'Conhecimento químico extraordinário advém com extraordinária responsabilidade', video: "https://www.youtube.com/embed/link" },
];
